name: Setup melange

inputs:
  version:
    description: Version of melange to install (latest, v0.48.2, etc.)
    default: latest
    required: true

runs:
  using: composite
  steps:
    - name: Install melange
      shell: bash
      run: |
        die() { printf '%s\n' "$*"; exit 1; }

        case '${{ inputs.version }}' in
        v*)
          TAG='${{ inputs.version }}'
          ;;
        latest*)
          tmp=$(mktemp)
          url='https://api.github.com/repos/chainguard-dev/melange/releases/latest'
          curl -fso "$tmp" -u ':${{ github.token }}' "$url" ||
            die "error in github api call for latest melange release"
          TAG=$(jq -r .tag_name <"$tmp") ||
            die "error parsing json from $url"
          test -n "$TAG" ||
            die "no melange release found"
          rm -f "$tmp"
          ;;
        esac

        case '${{ runner.os }}' in
        Linux) OS=linux ;;
        macOS) OS=darwin ;;
        *) die 'Unsupported os: ${{ runner.os }}' ;;
        esac

        case '${{ runner.arch }}' in
        X64) ARCH=amd64 ;;
        ARM64) ARCH=arm64 ;;
        *) die 'Unsupported arch: ${{ runner.arch }}' ;;
        esac

        curl -fsL "https://github.com/chainguard-dev/melange/releases/download/${TAG}/melange_${TAG#v}_${OS}_${ARCH}.tar.gz" \
          |tar xz --exclude LICENSE --strip-components=1 -C /usr/local/bin

        melange version

    - name: Create melange apparmor profile to enable unprivileged user namespaces
      if: runner.os == 'Linux'
      shell: bash
      run: |
        # https://github.com/chainguard-dev/melange/issues/1508
        sudo tee /etc/apparmor.d/melange >/dev/null <<EOF
        abi <abi/4.0>,
        include <tunables/global>
        /usr/local/bin/melange flags=(unconfined) {
          userns,
          include if exists <local/melange>
        }
        EOF

        sudo systemctl reload apparmor

    - name: Install bubblewrap
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get -qq install bubblewrap
