server.modules = (
	"mod_fastcgi",
	"mod_staticfile",
	"mod_rewrite",
	"mod_access"
)

server.tag = ""

server.port = 8000
server.errorlog = "/dev/stderr"
server.pid-file = "/dev/shm/lighttpd.pid"
server.upload-dirs = ("/dev/shm")

server.document-root = "/usr/share/webapps/glpi/public"

index-file.names = ("index.php")
static-file.exclude-extensions = (".php")

url.rewrite-if-not-file = ( "" => "/index.php${url.path}${qsa}" )

fastcgi.server = (
	".php" => ((
		"socket" => "/dev/shm/fcgi.socket",
		"bin-path" => "/usr/bin/php-cgi",
		"bin-copy-environment" => (
			"PATH",
			"USER",
			"PHP_FCGI_CHILDREN",
			"PHP_FCGI_MAX_REQUESTS"
		),
		"min-procs" => "1",
		"max-procs" => "1",
		"x-sendfile" => "enable",
		"x-sendfile-docroot" => ("/usr/share/webapps/glpi/public")
	))
)

$HTTP["url"] =~ "^/install/" {
	url.access-deny = ( "" )
}
