package:
  name: alps
  version: "0_git20251126"
  epoch: 0
  description: A simple and extensible webmail
  copyright:
    - license: MIT

pipeline:
  - uses: git-checkout
    with:
      repository: https://git.sr.ht/~migadu/alps
      branch: master
      expected-commit: bd6a860d88e9ee02fc051f8596b042e7381b38fa

  - uses: patch
    with:
      patches: default-theme.patch

  - uses: go/build
    environment:
      CGO_ENABLED: 0
    with:
      packages: ./cmd/alps
      output: alps
      strip: -s -w -buildid=
      ldflags: >
        -X main.themesPath=/usr/share/alps/themes

  - name: install themes
    runs: |
      mkdir -p ${{targets.contextdir}}/usr/share/alps
      cp -a themes ${{targets.contextdir}}/usr/share/alps

update:
  enabled: true
  git: {}
