package:
  name: alps
  version: "1"
  epoch: 0
  description: A simple and extensible webmail
  copyright:
    - license: MIT

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/migadu/alps/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha256: 11321dfd9ede5609c9cc02bcdfb55d537f330b0576589b79d2b774219e03f3ba

  - uses: go/build
    environment:
      CGO_ENABLED: 0
    with:
      packages: ./cmd/alps
      output: alps
      strip: -s -w -buildid=
      ldflags: |
        -X main.version=${{package.version}}
        -X main.date=$(date -d @"${SOURCE_DATE_EPOCH:-0}" -u '+%Y-%m-%dT%TZ')

update:
  enabled: true
  github:
    identifier: migadu/alps
    strip-prefix: v

test:
  pipeline:
    - runs: |
        set -o pipefail
        alps -version | grep 'alps ${{package.version}}'
