package:
  name: darkhttpd
  version: "1.17"
  epoch: 0
  description: When you need a web server in a hurry.
  copyright:
    - license: ISC

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - gcc
      - make

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/emikulic/darkhttpd/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha256: 4fee9927e2d8bb0a302f0dd62f9ff1e075748fa9f5162c9481a7a58b41462b56

  - uses: autoconf/make
    environment:
      LDFLAGS: -s -static -Wl,--gc-sections -flto

  - name: install
    runs: |
      install -Dm755 darkhttpd ${{targets.contextdir}}/usr/bin/darkhttpd

update:
  enabled: false
  github:
    identifier: emikulic/darkhttpd
    strip-prefix: v

test:
  pipeline:
    - runs: |
        set -o pipefail
        darkhttpd --help | grep darkhttpd/${{package.version}}
