package:
  name: grist
  version: "1.7.17"
  epoch: 0
  description: The evolution of spreadsheets
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - bash
      - musl-utils
      - nodejs
      - python3
  options:
    no-depends: true

environment:
  contents:
    packages:
      - bash
      - busybox
      - ca-certificates-bundle
      - gcc
      - make
      - python3
      - uv
      - yarn
  environment:
    YARN_ENABLE_GLOBAL_CACHE: true
    YARN_CACHE_FOLDER: /var/cache/melange/yarn

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/gristlabs/grist-core/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha256: 440f1f931741ebd9dade29b17ad7e36483a28f788cc3e9d7d4a5cb8c1689a296

  - uses: patch
    with:
      patches: python314.patch

  - name: install build dependencies
    runs: |
      yarn install --frozen-lockfile

  - name: build
    runs: |
      yarn run build:prod

  - name: install production dependencies
    runs: |
      yarn install --production --ignore-scripts --prefer-offline --frozen-lockfile

  - name: create sandbox venv
    environment:
      VIRTUAL_ENV: sandbox_venv3
    runs: |
      uv venv "$VIRTUAL_ENV"
      uv pip install -r sandbox/requirements.txt --no-deps --compile-bytecode

  - name: package
    runs: |
      tar c -C '${{package.srcdir}}' \
      --exclude '.lock' \
      --exclude 'README' \
      --exclude '*napi.node' \
      --exclude '*.a' \
      --exclude '*.o' \
      --exclude '*.glibc.node' \
      --exclude '*.md' \
      _build/ bin/ bower_components/ node_modules/ plugins/ sandbox/ sandbox_venv3/ static/ \
      |tar x
    working-directory: ${{targets.contextdir}}/usr/share/grist

update:
  enabled: true
  github:
    identifier: gristlabs/grist-core
    strip-prefix: v
