package:
  name: meshcentral
  version: "1.1.58"
  epoch: 0
  description: A full computer management web site
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - nodejs
  options:
    no-depends: true

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - jq
      - npm

vars:
  ldap: false
  ssh: false
  captcha: false
  recording: true
  multiplexor: true
  letsencrypt: false
  mqtt: false
  mysql: false
  mongodb: false
  postgres: true
  mariadb: true
  acebase: false
  sqlite3: false
  vault: false
  proxy: true
  smtp: true
  crowdsec: false
  prometheus: true
  encryption: false
  googledrive: false
  webdav: false
  s3: false
  wildleek: false
  yubikey: false
  twilio: false
  plivo: false
  telnyx: false
  telegram: false
  discord: false
  xmpp: false
  pushover: false
  zulip: false
  webpush: false
  firebase: false
  syslog: false

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/Ylianst/MeshCentral/archive/refs/tags/${{package.version}}.tar.gz
      expected-sha256: 551fc3c018c2db61b74e2ca9b5119aaa1b78bdd6f81553e169cf2c5cc6e35969

  - name: generate dependencies
    runs: |
      grep -oE "modules.push\('[@\/a-zA-Z0-9.-]+@[0-9.]+'\)" meshcentral.js |
        grep -o "'.*'" |
        tr -d "'" |
        sort -u |
        tee dependencies

  - name: include extra dependencies
    runs: "add_dep() {\n  _d=$(grep $1 dependencies); _t=$(mktemp -q); _n=${_d%@*}; _v=${_d##*@};\n  jq \".dependencies+={\\\"$_n\\\": \\\"$_v\\\"}\" package.json >\"$_t\" && mv \"$_t\" package.json\n}\n\n${{vars.ldap}} && add_dep ldapauth-fork\n${{vars.ssh}} && add_dep ssh2\n${{vars.captcha}} && add_dep svg-captcha\n${{vars.recording}} || ${{vars.multiplexor}} && add_dep image-size\n${{vars.letsencrypt}} && add_dep acme-client\n${{vars.mqtt}} && add_dep aedes\n${{vars.mysql}} && add_dep mysql2\n${{vars.mongodb}} && add_dep @mongodb-js/saslprep && add_dep mongodb\n${{vars.postgres}} && add_dep pg\n${{vars.mariadb}} && add_dep mariadb\n${{vars.acebase}} && add_dep acebase\n${{vars.sqlite3}} && add_dep sqlite3\n${{vars.vault}} && add_dep node-vault\n${{vars.proxy}} && add_dep https-proxy-agent\n${{vars.smtp}} && add_dep nodemailer\n${{vars.crowdsec}} && add_dep @crowdsec/express-bouncer\n${{vars.prometheus}} && add_dep prom-client\n${{vars.encryption}} && add_dep archiver-zip-encrypted\n${{vars.googledrive}} && add_dep googleapis\n${{vars.webdav}} && add_dep webdav        \n${{vars.s3}} && add_dep minio\n${{vars.wildleek}} && add_dep wildleek\n${{vars.yubikey}} && add_dep yub\n${{vars.twilio}} && add_dep twilio\n${{vars.plivo}} && add_dep plivo\n${{vars.telnyx}} && add_dep telnyx\n${{vars.telegram}} && add_dep telegram && add_dep input\n${{vars.discord}} && add_dep discord.js\n${{vars.xmpp}} && add_dep @xmpp/client\n${{vars.pushover}} && add_dep node-pushover\n${{vars.zulip}} && add_dep zulip\n${{vars.webpush}} && add_dep web-push\n${{vars.firebase}} && add_dep firebase-admin\n${{vars.syslog}} && add_dep modern-syslog\n"

  - name: install dependencies
    runs: |
      grep -E 'html-minifier-terser|jsdom|esprima' dependencies |
        xargs npm install -D -E --package-lock-only

      npm ci

  - name: translate
    runs: |
      cd translate
      node translate.js extractall
      node translate.js minifyall
      node translate.js translateall

  - name: prune dev dependencies
    runs: |
      npm prune --omit=dev

  - uses: patch
    with:
      patches: paths.patch

  - name: fix package.json permissions
    runs: |
      chmod 644 package.json

  - name: package
    runs: >
      install -dm755 ${{targets.contextdir}}/usr/share/meshcentral; tar c agents/ amt/ emails/ node_modules/ public/ rdp/ views/ *.js package-lock.json package.json LICENSE |tar x -C ${{targets.contextdir}}/usr/share/meshcentral


update:
  enabled: true
  github:
    identifier: Ylianst/MeshCentral
