package:
  name: ofelia
  version: "0.3.21"
  epoch: 0
  description: A docker job scheduler (aka. crontab for docker)
  copyright:
    - license: MIT

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/mcuadros/ofelia/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha256: ac2bb035bbb6780187db2056cc92ec3bf66156c34c66ff76c02c8574fe0ffa0d

  - uses: go/build
    environment:
      CGO_ENABLED: 0
    with:
      packages: .
      output: ofelia
      strip: -s -w -buildid=
      ldflags: |
        -X main.version=v${{package.version}}
        -X main.build=$(date -d @"${SOURCE_DATE_EPOCH:-0}" -u '+%Y-%m-%dT%TZ')

update:
  enabled: true
  github:
    identifier: mcuadros/ofelia
    strip-prefix: v

test:
  pipeline:
    - runs: |
        set -o pipefail
        ofelia | grep ${{package.version}}
