package:
  name: snappymail
  version: "2.38.2"
  epoch: 1
  description: Simple, modern & fast web-based email client
  copyright:
    - license: AGPL-3.0-only

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/the-djmaze/snappymail/releases/download/v${{package.version}}/snappymail-${{package.version}}.tar.gz
      expected-sha256: 71f1d8a9065cc9cf7ddd064f5c47cc7b255cb70e6a56713647fc73d4b79e33ec
      strip-components: 0
      delete: true
    working-directory: ${{targets.contextdir}}/usr/share/webapps/snappymail

  - name: theme
    runs: |
      rm -rf ${{targets.contextdir}}/usr/share/webapps/snappymail/snappymail/v/${{package.version}}/themes/*
      cp -a theme ${{targets.contextdir}}/usr/share/webapps/snappymail/snappymail/v/${{package.version}}/themes/Default

  - name: configurations
    runs: |
      install -Dm644 include.php ${{targets.contextdir}}/usr/share/doc/snappymail/include.php
      install -Dm644 lighttpd.conf ${{targets.contextdir}}/usr/share/doc/snappymail/lighttpd.conf
      install -Dm644 php.ini ${{targets.contextdir}}/usr/share/doc/snappymail/php.ini

update:
  enabled: true
  github:
    identifier: the-djmaze/snappymail
    strip-prefix: v
