package:
  name: traefik
  version: "3.7.8"
  epoch: 0
  description: The Cloud Native Application Proxy
  copyright:
    - license: MIT

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/traefik/traefik/releases/download/v${{package.version}}/traefik-v${{package.version}}.src.tar.gz
      expected-sha256: 3a725c0ead27fa512756acd57056ec4652420a9daceaa6d9c170bfbb25bf51f9

  - uses: go/build
    environment:
      CGO_ENABLED: 0
    with:
      packages: ./cmd/traefik
      output: traefik
      strip: -s -w -buildid=
      ldflags: |
        -X github.com/traefik/traefik/v3/pkg/version.Version=${{package.version}}
        -X github.com/traefik/traefik/v3/pkg/version.BuildDate=$(date -d @"${SOURCE_DATE_EPOCH:-0}" -u '+%Y-%m-%dT%TZ')

update:
  enabled: true
  github:
    identifier: traefik/traefik
    strip-prefix: v

test:
  pipeline:
    - runs: |
        set -o pipefail
        traefik version | grep ${{package.version}}
