package:
  name: traefik
  version: "3.6.9"
  epoch: 0
  description: The Cloud Native Application Proxy
  copyright:
    - license: MIT

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/traefik/traefik/releases/download/v${{package.version}}/traefik-v${{package.version}}.src.tar.gz
      expected-sha256: dd040144d2c5117de1572f7660904b810b5fa5c8182ad4ad1a884d9b0bda343d

  - uses: go/build
    environment:
      CGO_ENABLED: 0
    with:
      packages: ./cmd/traefik
      output: traefik
      strip: -s -w -buildid=
      ldflags: >-
        -X github.com/traefik/traefik/v3/pkg/version.Version=${{package.version}} -X github.com/traefik/traefik/v3/pkg/version.BuildDate=$(date -d @"${SOURCE_DATE_EPOCH:-0}" -u '+%Y-%m-%dT%TZ')

update:
  enabled: true
  github:
    identifier: traefik/traefik
    strip-prefix: v

test:
  pipeline:
    - runs: |
        set -o pipefail
        traefik version | grep ${{package.version}}
