package:
  name: webdav
  version: "5.13.0"
  epoch: 0
  description: A simple and standalone WebDAV server.
  copyright:
    - license: MIT

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/hacdias/webdav/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha256: e954f38b5445bb77150e5dd59181c58dc5dba0ac56b34a5b4909062381cdfdd6

  - uses: go/build
    environment:
      CGO_ENABLED: 0
    with:
      packages: .
      output: webdav
      strip: -s -w -buildid=
      ldflags: |
        -X github.com/hacdias/webdav/v5/cmd.version=${{package.version}}

update:
  enabled: true
  github:
    identifier: hacdias/webdav
    strip-prefix: v

test:
  pipeline:
    - runs: |
        set -o pipefail
        webdav version | grep ${{package.version}}
