package:
  name: webdav
  version: "5.14.2"
  epoch: 0
  description: A simple and standalone WebDAV server.
  copyright:
    - license: MIT

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/hacdias/webdav/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha256: aeaa640929b02d32645f5e856b7ac1f2eb282562496a2c207982113cd6fc607c

  - uses: go/build
    environment:
      CGO_ENABLED: 0
    with:
      packages: .
      output: webdav
      strip: -s -w -buildid=
      ldflags: |
        -X github.com/hacdias/webdav/v5/cmd.version=${{package.version}}

update:
  enabled: true
  github:
    identifier: hacdias/webdav
    strip-prefix: v

test:
  pipeline:
    - runs: |
        set -o pipefail
        webdav version | grep ${{package.version}}
