package:
  name: webdav
  version: "5.11.2"
  epoch: 0
  description: A simple and standalone WebDAV server.
  copyright:
    - license: MIT

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/hacdias/webdav/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha256: 75c6c2339237886d3745e0efd760de20a4b16add3543de9eb50ce3603151e5b3

  - uses: go/build
    environment:
      CGO_ENABLED: 0
    with:
      packages: .
      output: webdav
      strip: -s -w -buildid=
      ldflags: |
        -X github.com/hacdias/webdav/v5/cmd.version=${{package.version}}

update:
  enabled: true
  github:
    identifier: hacdias/webdav
    strip-prefix: v

test:
  pipeline:
    - runs: |
        set -o pipefail
        webdav version | grep ${{package.version}}
