---
name: Release

on:
  workflow_dispatch:
    inputs:
      images:
        required: false
        default: '*'
        description: images to release
      packages:
        required: false
        default: '*'
        description: packages

env:
  OCIREPO: 'ghcr.io/${{ github.repository }}'

jobs:

  prepare:
    name: prepare
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Matrix
        id: matrix
        run: |
          bin/matrix --deps "${{ github.event.inputs.packages }}" "${{ github.event.inputs.images }}"

  release:
    name: release ${{ matrix.I }} for ${{ matrix.A }}
    needs: prepare
    strategy:
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}
    permissions:
      contents: read
      packages: write
    runs-on: ${{ matrix.R }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Setup apko
        uses: ./.github/actions/setup-apko

      - name: Setup melange
        uses: ./.github/actions/setup-melange

      - name: Setup signing key
        run: |
          cat > local.rsa <<EOF
          ${{ secrets.SIGNING_KEY }}
          EOF

      - name: Login to GitHub Container Registry
        run: |
          apko login ghcr.io -u '${{ github.repository_owner }}' --password-stdin <<EOF
          ${{ github.token }}
          EOF

      - name: Generate build.ninja
        run: |
          bin/mkninja >build.ninja

      - name: Publish ${{ matrix.I }} for ${{ matrix.A }}
        run: |
          ninja -j 1 publish-${{ matrix.I }}-${{ matrix.A }}

      - name: Upload digest
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f  # v7.0.0
        with:
          name: digest-${{ matrix.I }}-${{ matrix.A }}
          path: digest*
          if-no-files-found: error
          retention-days: 3
          compression-level: 0

  merge:
    needs:
      - release
    permissions:
      packages: write
    runs-on: ubuntu-24.04
    steps:
      - name: Download digests
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  # v8.0.1
        with:
          pattern: |
            digest-*
          merge-multiple: true

      - name: Login to GitHub Container Registry
        run: |
          docker login --password-stdin -u ${{ github.repository_owner }} ghcr.io <<EOF
          ${{ github.token }}
          EOF

      - name: Create image list
        shell: python
        run: |
          from pathlib import Path

          index = set()

          for f in Path.cwd().glob("digest+*"):
              parts = f.name.split("+")
              image = f"{parts[1]}:{parts[2]}"
              if image not in index:
                  index.add(image)

          with open("images.txt", "w", encoding="utf-8") as f:
              for image in index:
                  f.write(f"{image}\n")

      - name: Create manifest list and push
        run: |
          while IFS=: read -r image tag; do
              docker buildx imagetools create -t "$OCIREPO"/"$image":"$tag" $(cat digest+"$image"+"$tag"+*)
          done < images.txt
