---
name: Update packages from GitHub

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:

  update:
    name: update
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Setup melu
        uses: ./.github/actions/setup-melu
        with:
          version: v0.1.0

      - name: Setup melange
        uses: ./.github/actions/setup-melange

      - name: Update packages
        env:
          GH_TOKEN: ${{ github.token }}
          GITHUB_TOKEN: ${{ github.token }}
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        run: |
          melu -query-github packages |while IFS=, read -r f p v nv ncommit
          do
            if [ X"$v" == X"$nv" ]; then
              continue
            fi

            melange bump "$f" "$nv" --expected-commit "$ncommit" 2>&1 \
              |tee melange-bump.err
            if [ $? -ne 0 ]; then
              gh issue create \
                --title "$p/$nv package update" \
                --label "$p,update" \
                --body-file melange-bump.err
              continue
            fi

            git checkout -b "update/$p-$nv"
            git add "$f"
            git commit -m "$p/$nv package update"
            git push origin "update/$p-$nv"

            pr=$(gh pr create \
              --title "$p/$nv package update" \
              --label "$p,update" \
              --body "Automatic update of $p package version to $nv"
              --base master)

            gh pr merge "${pr##*/}" --squash

            git checkout master
            git branch -D "update/$p-$nv"
          done
